# JANYA Table
CREATE TABLE JANYA (
ID INT PRIMARY KEY,
RAGA_NAME TEXT NOT NULL,
MELAKARTA INT NOT NULL,
SCALE TEXT NOT NULL,
FOREIGN KEY (MELAKARTA) REFERENCES MELAKARTAS(ID)
);


# MELAKARTA  TABLE

CREATE TABLE MELAKARTAS (
ID INT PRIMARY KEY,
NAME TEXT NOT NULL,
SCALE TEXT NOT NULL
);
